// LCES Roster Data — embedded snapshot (used on both local file:// and GitHub Pages)
// roster.json is deliberately NOT deployed to GitHub Pages to protect uncensored gamertags.
window.__rosterData = [
  {"badge":1,"gamertag":"NC Sheriff","display":"NC Sh****f","status":"pending"},
  {"badge":2,"gamertag":"huskerguy7","display":"husk****y7","status":"pending"},
  {"badge":3,"gamertag":"stevenkb6720","display":"stev**kb6***","status":"pending"},
  {"badge":4,"gamertag":"CALIKILLER33","display":"CALIK*****33","status":"pending"},
  {"badge":5,"gamertag":"Chad4887","display":"Ch*d**87","status":"pending"},
  {"badge":6,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":7,"gamertag":"Berget13","display":"Ber**t13","status":"pending"},
  {"badge":8,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":9,"gamertag":"JJMON100","display":"JJM**100","status":"pending"},
  {"badge":10,"gamertag":"DrGreenthumb49","display":"DrGr******mb49","status":"pending"},
  {"badge":11,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":12,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":13,"gamertag":"Kill2thrill0","display":"Kil*2th****0","status":"pending"},
  {"badge":14,"gamertag":"Melodik","display":"Mel**ik","status":"pending"},
  {"badge":15,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":16,"gamertag":"JonnyAndrews","display":"Jon**A****ws","status":"pending"},
  {"badge":17,"gamertag":"PTY997","display":"PTY***","status":"pending"},
  {"badge":18,"gamertag":"Naytt","display":"Nay**","status":"pending"},
  {"badge":19,"gamertag":"Tepus Mori","display":"Tep*****ri","status":"pending"},
  {"badge":20,"gamertag":"Brynley","display":"Bry**ey","status":"pending"},
  {"badge":21,"gamertag":"Ewest","display":"Ewe**","status":"pending"},
  {"badge":22,"gamertag":"ChevyRacing88","display":"Che**R****g8*","status":"pending"},
  {"badge":23,"gamertag":"GTS6","display":"GTS*","status":"pending"},
  {"badge":24,"gamertag":"AlphaSierra172","display":"Alp**S****a17*","status":"pending"},
  {"badge":25,"gamertag":"REAPER MC","display":"REA****MC","status":"pending"},
  {"badge":26,"gamertag":"Cpt Reynolds SC","display":"Cpt*R*y******SC","status":"pending"},
  {"badge":27,"gamertag":"Reap the Ghost","display":"Rea*****G***st","status":"pending"},
  {"badge":28,"gamertag":"DeathBringer93","display":"De***B****er9*","status":"pending"},
  {"badge":29,"gamertag":"lonesoldier12","display":"lone*******12","status":"pending"},
  {"badge":30,"gamertag":"Starbug","display":"Sta**ug","status":"pending"},
  {"badge":31,"gamertag":"skrilla93","display":"skr****93","status":"pending"},
  {"badge":32,"gamertag":"pow3rhous3","display":"pow**h**s3","status":"pending"},
  {"badge":33,"gamertag":"DevenOB","display":"Dev**OB","status":"pending"},
  {"badge":34,"gamertag":"Stevo123abc","display":"Ste******bc","status":"pending"},
  {"badge":35,"gamertag":"scaledwag","display":"sca****ag","status":"pending"},
  {"badge":36,"gamertag":"ll Carroll ll","display":"ll ********ll","status":"pending"},
  {"badge":37,"gamertag":"CowboyD Eng6ine","display":"Cow**********ne","status":"pending"},
  {"badge":38,"gamertag":"V Taylor V","display":"V T***** V","status":"pending"},
  {"badge":39,"gamertag":"tomster2807","display":"tom******07","status":"pending"},
  {"badge":40,"gamertag":"adirtyhobo","display":"adi*****bo","status":"pending"},
  {"badge":41,"gamertag":"crasha9","display":"cra**a9","status":"pending"},
  {"badge":42,"gamertag":"burtoni uk","display":"bur*****uk","status":"pending"},
  {"badge":43,"gamertag":"DrewCephus","display":"Dre*****us","status":"pending"},
  {"badge":44,"gamertag":"downmaster","display":"dow*****er","status":"pending"},
  {"badge":45,"gamertag":"Anditek","display":"And**ek","status":"pending"},
  {"badge":46,"gamertag":"kgp1191","display":"kgp**91","status":"pending"},
  {"badge":47,"gamertag":"Killa0611","display":"Kil****11","status":"pending"},
  {"badge":48,"gamertag":"BornASurvivor","display":"Bor********or","status":"pending"},
  {"badge":49,"gamertag":"infamousdirt","display":"inf*******rt","status":"pending"},
  {"badge":50,"gamertag":"Guyana503Official","display":"Guy************al","status":"pending"},
  {"badge":51,"gamertag":"Prerecordedlive","display":"Pre**********ve","status":"pending"},
  {"badge":52,"gamertag":"Homeless Box","display":"Hom*******ox","status":"pending"},
  {"badge":53,"gamertag":"Alkal1neTri0","display":"Alk*******i0","status":"pending"},
  {"badge":54,"gamertag":"STRYKER397","display":"STR*****97","status":"pending"},
  {"badge":55,"gamertag":"darkmotive","display":"dar*****ve","status":"pending"},
  {"badge":56,"gamertag":"Mr. Slappy","display":"Mr.*****py","status":"pending"},
  {"badge":57,"gamertag":"Bob123","display":"Bob***","status":"pending"},
  {"badge":58,"gamertag":"redwards","display":"red***ds","status":"pending"},
  {"badge":59,"gamertag":"Young Gangstars","display":"You**********rs","status":"pending"},
  {"badge":60,"gamertag":"Von Schmitt","display":"Von******tt","status":"pending"},
  {"badge":61,"gamertag":"FDMT18","display":"FDM***","status":"pending"},
  {"badge":62,"gamertag":"police182","display":"pol****82","status":"pending"},
  {"badge":63,"gamertag":"l33t 0wn3r","display":"l33t 0wn3r","status":"active"},
  {"badge":64,"gamertag":"Kfperin","display":"Kfp**in","status":"pending"},
  {"badge":65,"gamertag":"Serimos6","display":"Ser***s6","status":"pending"},
  {"badge":66,"gamertag":"johnnygta4","display":"joh*****a4","status":"pending"},
  {"badge":67,"gamertag":"lockxxheed","display":"loc*****ed","status":"pending"},
  {"badge":68,"gamertag":"FeArLeS InFern0","display":"FeA**********n0","status":"pending"},
  {"badge":69,"gamertag":"halo12master","display":"hal*******er","status":"pending"},
  {"badge":70,"gamertag":"Yankees2122","display":"Yan******22","status":"pending"},
  {"badge":71,"gamertag":"BBF15","display":"BBF**","status":"pending"},
  {"badge":72,"gamertag":"Low Rent9","display":"Low****t9","status":"pending"},
  {"badge":73,"gamertag":"R0CKSTAR3N3RGY","display":"R0C*********GY","status":"pending"},
  {"badge":74,"gamertag":"Lance1031","display":"Lan****31","status":"pending"},
  {"badge":75,"gamertag":"Hawk0251","display":"Haw***51","status":"pending"},
  {"badge":76,"gamertag":"Delta Roughneks","display":"Del**********ks","status":"pending"},
  {"badge":77,"gamertag":"Firemike47","display":"Fir*****47","status":"pending"},
  {"badge":78,"gamertag":"HAZARDtehFrea","display":"HAZ********ea","status":"pending"},
  {"badge":79,"gamertag":"dukheddd","display":"duk***dd","status":"pending"},
  {"badge":80,"gamertag":"Deblo","display":"Deb**","status":"pending"},
  {"badge":81,"gamertag":"jaycat","display":"jay***","status":"pending"},
  {"badge":82,"gamertag":"didikong420","display":"did******20","status":"pending"},
  {"badge":83,"gamertag":"budatoker 305","display":"bud********05","status":"pending"},
  {"badge":84,"gamertag":"PLASMASTORM","display":"PLA******RM","status":"pending"},
  {"badge":85,"gamertag":"hoffasgrave","display":"hof******ve","status":"pending"},
  {"badge":86,"gamertag":"GreekStallion","display":"Gre********on","status":"pending"},
  {"badge":87,"gamertag":"Viperfella","display":"Vip*****la","status":"pending"},
  {"badge":88,"gamertag":"MR FMM GENERAL","display":"MR *********AL","status":"pending"},
  {"badge":89,"gamertag":"BLAZ3D 863","display":"BLA*****63","status":"pending"},
  {"badge":90,"gamertag":"x O Ramirez x","display":"x O******** x","status":"pending"},
  {"badge":91,"gamertag":"o4wheelerd","display":"o4w*****rd","status":"pending"},
  {"badge":92,"gamertag":"FMMGENERAL","display":"FMM*****AL","status":"pending"},
  {"badge":93,"gamertag":"MontrealFan94","display":"Mon********94","status":"pending"},
  {"badge":94,"gamertag":"dave1208","display":"dav***08","status":"pending"},
  {"badge":95,"gamertag":"oRAWLIKESTEAKo","display":"oRA*********Ko","status":"pending"},
  {"badge":96,"gamertag":"Quietchaos2","display":"Qui******s2","status":"pending"},
  {"badge":97,"gamertag":"Officer Joey 016","display":"Off***********16","status":"pending"},
  {"badge":98,"gamertag":"Rondel Jonathan","display":"Ron**********an","status":"pending"},
  {"badge":99,"gamertag":"darza310","display":"dar***10","status":"pending"},
  {"badge":100,"gamertag":"reaper0322","display":"rea*****22","status":"pending"},
  {"badge":101,"gamertag":"xlair","display":"xla**","status":"pending"},
  {"badge":102,"gamertag":"alexbeast5226","display":"ale********26","status":"pending"},
  {"badge":103,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":104,"gamertag":"DUT00","display":"DUT**","status":"pending"},
  {"badge":105,"gamertag":"x iSniped x","display":"x i****** x","status":"pending"},
  {"badge":106,"gamertag":"XxVinny13","display":"XxV****13","status":"pending"},
  {"badge":107,"gamertag":"Pyro1145","display":"Pyr***45","status":"pending"},
  {"badge":108,"gamertag":"A-Rod","display":"A-R**","status":"pending"},
  {"badge":109,"gamertag":"USmarshal505","display":"USm*******05","status":"pending"},
  {"badge":110,"gamertag":"iSank","display":"iSa**","status":"pending"},
  {"badge":111,"gamertag":"Youngster809","display":"You*******09","status":"pending"},
  {"badge":112,"gamertag":"Ed251191","display":"Ed2***91","status":"pending"},
  {"badge":113,"gamertag":"dallashero421","display":"dal********21","status":"pending"},
  {"badge":114,"gamertag":"cheesemonkyman","display":"che*********an","status":"pending"},
  {"badge":115,"gamertag":"XxB ROD116xX","display":"XxB*******xX","status":"pending"},
  {"badge":116,"gamertag":"iMurder Scrubs","display":"iMu*********bs","status":"pending"},
  {"badge":117,"gamertag":"SoulSniper","display":"Sou*****er","status":"pending"},
  {"badge":118,"gamertag":"MR.PALOS","display":"MR.***OS","status":"pending"},
  {"badge":119,"gamertag":"carver60","display":"car***60","status":"pending"},
  {"badge":120,"gamertag":"delta echo","display":"del*****ho","status":"pending"},
  {"badge":121,"gamertag":"Vanillaohman44","display":"Van*********44","status":"pending"},
  {"badge":122,"gamertag":"apollosky","display":"apo****ky","status":"pending"},
  {"badge":123,"gamertag":"The Jackel 1739","display":"The**********39","status":"pending"},
  {"badge":124,"gamertag":"plumpinator","display":"plu******or","status":"pending"},
  {"badge":125,"gamertag":"GDN smp91","display":"GDN****91","status":"pending"},
  {"badge":126,"gamertag":"Scheffy1777","display":"Sch******77","status":"pending"},
  {"badge":127,"gamertag":"Officer Tischler","display":"Off***********er","status":"pending"},
  {"badge":128,"gamertag":"GMR2GMR","display":"GMR**MR","status":"pending"},
  {"badge":129,"gamertag":"lbj2372","display":"lbj**72","status":"pending"},
  {"badge":130,"gamertag":"DirtyHarry","display":"Dir*****ry","status":"pending"},
  {"badge":131,"gamertag":"Aqua Swede","display":"Aqu*****de","status":"pending"},
  {"badge":132,"gamertag":"zipperman","display":"zip****an","status":"pending"},
  {"badge":133,"gamertag":"ziggy","display":"zig**","status":"pending"},
  {"badge":134,"gamertag":"Peter Boii","display":"Pet*****ii","status":"pending"},
  {"badge":135,"gamertag":"Dudrick","display":"Dud**ck","status":"pending"},
  {"badge":136,"gamertag":"NYPD12293","display":"NYP****93","status":"pending"},
  {"badge":137,"gamertag":"XxBrAdMaN94xX","display":"XxB********xX","status":"pending"},
  {"badge":138,"gamertag":"WPPD 13","display":"WPP**13","status":"pending"},
  {"badge":139,"gamertag":"pieterXBoss","display":"pie******ss","status":"pending"},
  {"badge":140,"gamertag":"cavs4life776","display":"cav*******76","status":"pending"},
  {"badge":141,"gamertag":"bobasarus7","display":"bob*****s7","status":"pending"},
  {"badge":142,"gamertag":"Honorordeath999","display":"Hon**********99","status":"pending"},
  {"badge":143,"gamertag":"Aim2Gain","display":"Aim***in","status":"pending"},
  {"badge":144,"gamertag":"callumv/xSXYBRITx","display":"cal************Tx","status":"pending"},
  {"badge":145,"gamertag":"VoltaicYapper","display":"Vol********er","status":"pending"},
  {"badge":146,"gamertag":"Gixxerlover1","display":"Gix*******r1","status":"pending"},
  {"badge":147,"gamertag":"juliankern","display":"jul*****rn","status":"pending"},
  {"badge":148,"gamertag":"Beon 911","display":"Beo***11","status":"pending"},
  {"badge":149,"gamertag":"PVfirefighter38","display":"PVf**********38","status":"pending"},
  {"badge":150,"gamertag":"PoliceExplorer9","display":"Pol**********r9","status":"pending"},
  {"badge":151,"gamertag":"firecop41617/iceman61741","display":"fir*******************41","status":"pending"},
  {"badge":152,"gamertag":"longhorn400","display":"lon******00","status":"pending"},
  {"badge":153,"gamertag":"C H I2 iii S x","display":"C H********* x","status":"pending"},
  {"badge":154,"gamertag":"liftoff","display":"lif**ff","status":"pending"},
  {"badge":155,"gamertag":"caspa156","display":"cas***56","status":"pending"},
  {"badge":156,"gamertag":"cbassmiami","display":"cba*****mi","status":"pending"},
  {"badge":157,"gamertag":"skiledkilla117","display":"ski*********17","status":"pending"},
  {"badge":158,"gamertag":"Xtromist","display":"Xtr***st","status":"pending"},
  {"badge":159,"gamertag":"Maurice el jefe","display":"Mau**********fe","status":"pending"},
  {"badge":160,"gamertag":"DsL Quality","display":"DsL******ty","status":"pending"},
  {"badge":161,"gamertag":"ACanadianDude","display":"ACa********de","status":"pending"},
  {"badge":162,"gamertag":"GONZOAB/iCory Gunz","display":"GON*************nz","status":"pending"},
  {"badge":163,"gamertag":"mitchell1621","display":"mit*******21","status":"pending"},
  {"badge":164,"gamertag":"NullLimitless","display":"Nul********ss","status":"pending"},
  {"badge":165,"gamertag":"xWel5hA55a55inx","display":"xWe**********nx","status":"pending"},
  {"badge":166,"gamertag":"Original Fusion","display":"Ori**********on","status":"pending"},
  {"badge":167,"gamertag":"xRIPx Chief","display":"xRI******ef","status":"pending"},
  {"badge":168,"gamertag":"Nah goo yen","display":"Nah******en","status":"pending"},
  {"badge":169,"gamertag":"daveted788","display":"dav*****88","status":"pending"},
  {"badge":170,"gamertag":"APDExplorer10","display":"APD********10","status":"pending"},
  {"badge":171,"gamertag":"JJ306","display":"JJ3**","status":"pending"},
  {"badge":172,"gamertag":"Royale Bond 007","display":"Roy**********07","status":"pending"},
  {"badge":173,"gamertag":"zan2000","display":"zan**00","status":"pending"},
  {"badge":174,"gamertag":"Jesse JK Kraft","display":"Jes*********ft","status":"pending"},
  {"badge":175,"gamertag":"RollinPCH","display":"Rol****CH","status":"pending"},
  {"badge":176,"gamertag":"N2L Fatality","display":"N2L*******ty","status":"pending"},
  {"badge":177,"gamertag":"Boboape9966","display":"Bob******66","status":"pending"},
  {"badge":178,"gamertag":"matty92ace","display":"mat*****ce","status":"pending"},
  {"badge":179,"gamertag":"DGowns","display":"DGo***","status":"pending"},
  {"badge":180,"gamertag":"VR9497","display":"VR9***","status":"pending"},
  {"badge":181,"gamertag":"UGC Sure Shot","display":"UGC********ot","status":"pending"},
  {"badge":182,"gamertag":"ITZ ROGUESTATUS","display":"ITZ**********US","status":"pending"},
  {"badge":183,"gamertag":"TheoxyCrash95","display":"The********95","status":"pending"},
  {"badge":184,"gamertag":"Hel Destruction","display":"Hel**********on","status":"pending"},
  {"badge":185,"gamertag":"HBR x BlitZz","display":"HBR*******Zz","status":"pending"},
  {"badge":186,"gamertag":"slickspencer8","display":"sli********r8","status":"pending"},
  {"badge":187,"gamertag":"ThaSituation188","display":"Tha**********88","status":"pending"},
  {"badge":188,"gamertag":"Schonely88","display":"Sch*****88","status":"pending"},
  {"badge":189,"gamertag":"NiteFlash91","display":"Nit******91","status":"pending"},
  {"badge":190,"gamertag":"marshmallowbomb","display":"mar**********mb","status":"pending"},
  {"badge":191,"gamertag":"Jake232","display":"Jak**32","status":"pending"},
  {"badge":192,"gamertag":"SnoopShady420","display":"Sno********20","status":"pending"},
  {"badge":193,"gamertag":"racer0940","display":"rac****40","status":"pending"},
  {"badge":194,"gamertag":"Emoney562","display":"Emo****62","status":"pending"},
  {"badge":195,"gamertag":"BGowns","display":"BGo***","status":"pending"},
  {"badge":196,"gamertag":"fishforlife2468","display":"fis**********68","status":"pending"},
  {"badge":197,"gamertag":"Spoonz_Elite","display":"Spo*******te","status":"pending"},
  {"badge":198,"gamertag":"UnitX22","display":"Uni**22","status":"pending"},
  {"badge":199,"gamertag":"oooHAYABUSAooo","display":"ooo*********oo","status":"pending"},
  {"badge":200,"gamertag":"Negative Risk","display":"Neg********sk","status":"pending"},
  {"badge":201,"gamertag":"XX86SNIPE86XX","display":"XX8********XX","status":"pending"},
  {"badge":202,"gamertag":"Dinozzo x187x","display":"Din********7x","status":"pending"},
  {"badge":203,"gamertag":"killarob917","display":"kil******17","status":"pending"},
  {"badge":204,"gamertag":"ASOC xGENERALx","display":"ASO*********Lx","status":"pending"},
  {"badge":205,"gamertag":"Officer Adam","display":"Off*******am","status":"pending"},
  {"badge":206,"gamertag":"Patrick1237","display":"Pat******37","status":"pending"},
  {"badge":207,"gamertag":"munoz 001","display":"mun****01","status":"pending"},
  {"badge":208,"gamertag":"SRidgeway3","display":"SRi*****y3","status":"pending"},
  {"badge":209,"gamertag":"Misslemoose","display":"Mis******se","status":"pending"},
  {"badge":210,"gamertag":"wwiifanatic28","display":"wwi********28","status":"pending"},
  {"badge":211,"gamertag":"desert eagle158","display":"des**********58","status":"pending"},
  {"badge":212,"gamertag":"x THE GREASER x","display":"x T********** x","status":"pending"},
  {"badge":213,"gamertag":"Jo3yDud3x23","display":"Jo3******23","status":"pending"},
  {"badge":214,"gamertag":"MAGMUHH","display":"MAG**HH","status":"pending"},
  {"badge":215,"gamertag":"xUSMC SSGTx","display":"xUS******Tx","status":"pending"},
  {"badge":216,"gamertag":"Capt Daisy","display":"Cap*****sy","status":"pending"},
  {"badge":217,"gamertag":"vVJeSUSFrEaKVv","display":"vVJ*********Vv","status":"pending"},
  {"badge":218,"gamertag":"JPM007","display":"JPM***","status":"pending"},
  {"badge":219,"gamertag":"MHTBravo","display":"MHT***vo","status":"pending"},
  {"badge":220,"gamertag":"LoganB613","display":"Log****13","status":"pending"},
  {"badge":221,"gamertag":"xXManATeeXx","display":"xXM******Xx","status":"pending"},
  {"badge":222,"gamertag":"Bronz186","display":"Bro***86","status":"pending"},
  {"badge":223,"gamertag":"BLUEelmoZZZZZ","display":"BLU********ZZ","status":"pending"},
  {"badge":224,"gamertag":"Pure VVebbster","display":"Pur*********er","status":"pending"},
  {"badge":225,"gamertag":"x SteaD","display":"x S**aD","status":"pending"},
  {"badge":226,"gamertag":"The Boss3185","display":"The*******85","status":"pending"},
  {"badge":227,"gamertag":"TF 141 Stephen","display":"TF *********en","status":"pending"},
  {"badge":228,"gamertag":"NSJ bped","display":"NSJ***ed","status":"pending"},
  {"badge":229,"gamertag":"Pwnisher James","display":"Pwn*********es","status":"pending"},
  {"badge":230,"gamertag":"Frostman100","display":"Fro******00","status":"pending"},
  {"badge":231,"gamertag":"TyBacca20","display":"TyB****20","status":"pending"},
  {"badge":232,"gamertag":"Chazzy B","display":"Cha*** B","status":"pending"},
  {"badge":233,"gamertag":"BACKDRAFT 5163","display":"BAC*********63","status":"pending"},
  {"badge":234,"gamertag":"Manny Year13","display":"Man*******13","status":"pending"},
  {"badge":235,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":236,"gamertag":"x ToXiC x ReCoN","display":"x T**********oN","status":"pending"},
  {"badge":237,"gamertag":"SupaWhiteyMan","display":"Sup********an","status":"pending"},
  {"badge":238,"gamertag":"Tryhard Enigma","display":"Try*********ma","status":"pending"},
  {"badge":239,"gamertag":"Combat Carlton","display":"Com*********on","status":"pending"},
  {"badge":240,"gamertag":"NotAHeroBassist","display":"Not**********st","status":"pending"},
  {"badge":241,"gamertag":"Dilated420","display":"Dil*****20","status":"pending"},
  {"badge":242,"gamertag":"PietThePenguin","display":"Pie*********in","status":"pending"},
  {"badge":243,"gamertag":"Byzantine95","display":"Byz******95","status":"pending"},
  {"badge":244,"gamertag":"JSFxDovahkiin","display":"JSF********in","status":"pending"},
  {"badge":245,"gamertag":"RESERVED","display":"RESERVED","status":"pending"},
  {"badge":246,"gamertag":"Bks05","display":"Bks**","status":"pending"},
  {"badge":247,"gamertag":"ScramblesRSG","display":"Scr*******SG","status":"pending"},
  {"badge":248,"gamertag":"Devil Dogs101","display":"Dev********01","status":"pending"},
  {"badge":249,"gamertag":"groom112","display":"gro***12","status":"pending"},
  {"badge":250,"gamertag":"FaTaLiTy FlAmE","display":"FaT*********mE","status":"pending"},
  {"badge":251,"gamertag":"Chrome Cracker","display":"Chr*********er","status":"pending"}
];
